/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package farmserver;

import java.io.*;
import java.util.StringTokenizer;
/**
 *
 * @author jamiehaywood
 */
public class RegisterUser extends javax.swing.JFrame {

    /**
     * Creates new form RegisterUser
     */
    public RegisterUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_username = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lbl_pw1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lbl_pw2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(475, 400));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("Register a New User");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setText("Username:");

        lbl_username.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel3.setText("Password:");

        lbl_pw1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel4.setText("Confirm Password:");

        lbl_pw2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_pw2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_pw1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_username, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbl_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_pw1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(lbl_pw2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterUser().setVisible(true);
            }
        });
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                //Check all text fields are filled
        String un, pw1, pw2;
               
        if (!"".equals(lbl_pw1.getText()) && !"".equals(lbl_pw2.getText()) && !"".equals(lbl_username.getText())) {
            un = lbl_username.getText();
            pw1 = lbl_pw1.getText();
            pw2 = lbl_pw2.getText();
            Boolean pwEqual = pw1.equals(pw2);
            //Call validation function
            if (pwEqual && isUNUnique(un)) {
                //Write to file
                registerUser(un, pw1);
                //Redirect to login form
                loginGUI loginForm = new loginGUI();
                loginForm.setVisible(true);
                this.setVisible(false);
            } else {
                //Notify user of error
                System.err.println("Error!");
        }
        } else {
            System.out.println("Please fill in all values");
            return;
        }
        
       
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public static String path = "/Users/jamiehaywood/GitProjects/farm-server/FarmServer/src/farmserver/logins.txt";
    
    private void registerUser(String un, String pw) { //registerUser is called to write a new username and password to the login text file
      //The 2 parameters are the username and password for the new account
        try {
            FileWriter fout = new FileWriter(path, true);
            PrintWriter pout = new PrintWriter(fout, true);                

            String loginString = un + ":" + pw;
            pout.println(loginString);         
            pout.close();
            
            System.out.println("Saved - " + un);

            } catch (IOException e) {

            }
    }
    
    private Boolean isUNUnique(String UN){
        //Read in all usernames
        String inUN, tempUN = null;
        try {
                FileReader fin = new FileReader(path);
                BufferedReader din = new BufferedReader(fin);
            while((inUN = din.readLine()) != null) {
                
                StringTokenizer st = new StringTokenizer(inUN, ":");
                
                if (st.hasMoreTokens()){
                    tempUN = st.nextToken().trim();
                    String PW = st.nextToken().trim();
                }
                //System.out.println(tempUN);
                

                if (tempUN.contentEquals(UN)) {
                    din.close();
                    return false;
                }        
            }
            return true;
        } catch (IOException e) {
                System.err.println("Error! - " + e.getMessage());
                return false ;
        }
        //If UN matches any username return false   
        //If not return true
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField lbl_pw1;
    private javax.swing.JTextField lbl_pw2;
    private javax.swing.JTextField lbl_username;
    // End of variables declaration//GEN-END:variables
}
